{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openkb.fullname" . }}
  labels:
    {{- include "openkb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openkb.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}
