param(
  [string]$DifyDbContainer = "docker-db_postgres-1",
  [string]$DifyDatabase = "dify",
  [string]$OutputPath = ".codex-runtime/openkb-local-models.ps1"
)

$ErrorActionPreference = "Stop"

function Get-PgDumpTableData {
  param([string]$Table)
  & wsl.exe bash -lc "docker exec $DifyDbContainer pg_dump -U postgres -d $DifyDatabase -t $Table --data-only --column-inserts"
  if ($LASTEXITCODE -ne 0) {
    throw "Failed to inspect Dify table $Table from $DifyDbContainer."
  }
}

function Get-SqlQuotedValues {
  param([string]$InsertLine)
  $matches = [regex]::Matches($InsertLine, "'((?:''|[^'])*)'")
  $values = @()
  foreach ($match in $matches) {
    $values += $match.Groups[1].Value.Replace("''", "'")
  }
  return $values
}

function Resolve-OpenKBChatEndpoint {
  param([string]$EndpointUrl)
  $normalized = $EndpointUrl.Trim().TrimEnd("/")
  if (-not $normalized) {
    return "https://api.deepseek.com/v1/chat/completions"
  }
  if ($normalized -match "/(v1/)?chat/completions$") {
    return $normalized
  }
  return "$normalized/v1/chat/completions"
}

$defaultModelDump = Get-PgDumpTableData "tenant_default_models"
$llmLine =
  $defaultModelDump |
  Where-Object { $_ -like "INSERT INTO public.tenant_default_models*" -and $_ -like "*'llm'*" } |
  Select-Object -First 1

if (-not $llmLine) {
  throw "No Dify tenant_default_models row with model_type=llm was found."
}

$llmValues = Get-SqlQuotedValues $llmLine
if ($llmValues.Count -lt 5) {
  throw "Could not parse Dify default LLM row."
}

$providerName = $llmValues[2]
$modelName = $llmValues[3]

$credentialDump = Get-PgDumpTableData "provider_credentials"
$providerCredentialLine =
  $credentialDump |
  Where-Object { $_ -like "INSERT INTO public.provider_credentials*" -and $_ -like "*'$providerName'*" } |
  Select-Object -First 1

$endpoint = "https://api.deepseek.com/v1/chat/completions"
if ($providerCredentialLine) {
  $credentialValues = Get-SqlQuotedValues $providerCredentialLine
  if ($credentialValues.Count -ge 5) {
    try {
      $encryptedConfig = $credentialValues[4] | ConvertFrom-Json
      if ($encryptedConfig.endpoint_url) {
        $endpoint = Resolve-OpenKBChatEndpoint ([string]$encryptedConfig.endpoint_url)
      }
    } catch {
      Write-Warning "Could not parse Dify provider credential metadata; using DeepSeek default endpoint."
    }
  }
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$resolvedOutputPath = Join-Path $repoRoot $OutputPath
$outputDir = Split-Path -Parent $resolvedOutputPath
if (-not (Test-Path -LiteralPath $outputDir)) {
  New-Item -ItemType Directory -Path $outputDir | Out-Null
}

$content = @(
  "# Generated by scripts/sync-dify-llm-local.ps1."
  "# This file intentionally does not store OPENKB_LLM_API_KEY."
  '$env:OPENKB_LLM_REQUEST_FORMAT = "openai_chat_completions"'
  "`$env:OPENKB_LLM_ENDPOINT = `"$endpoint`""
  "`$env:OPENKB_LLM_MODEL = `"$modelName`""
)

Set-Content -LiteralPath $resolvedOutputPath -Value $content -Encoding UTF8

Write-Host "Synced Dify default LLM for OpenKB local source mode:"
Write-Host "  provider: $providerName"
Write-Host "  model: $modelName"
Write-Host "  endpoint: $endpoint"
Write-Host "  env file: $resolvedOutputPath"
Write-Host "Set OPENKB_LLM_API_KEY in the launching shell or another ignored local env source."

